version: "2"
services:
        web:
          entrypoint: /code/wait-for-it.sh db
          build: .
          command: "python manage.py runserver 0.0.0.0:8000"
          volumes:
            - .:/code
          ports:
            - "8000:8000"
          links:
            - db
          depends_on:
            - db
            - migration
        migration:
          entrypoint: /code/wait-for-it.sh db
          build: .
          command: "python manage.py migrate"
          volumes:
            - .:/code
          links:
            - db
          depends_on:
            - db
        db:
          image: postgres
          volumes_from:
            - pg_data
        pg_data:
          image: pg_data
