# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Retweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('username', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('tweet_id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('text_content', models.CharField(auto_created=True, max_length=128)),
                ('username', models.CharField(auto_created=True, max_length=128)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='retweet',
            name='related_tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweet'),
        ),
        migrations.AddField(
            model_name='like',
            name='related_tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='twitter.Tweet'),
        ),
    ]
